### ISSUE TITLE
Invalid redirect_uri with monday_auth()

### ISSUE THREAD

**Issue by mattroumaya** [lynuhs/MondayR#1]
Thanks for developing this package! I'm using SSO with my workplace, and unable to authenticate: 

In the console I run: 

```r
monday_auth("client id", "client secret")

```

...which opens a browser, and I receive the error message: `{"error":"invalid_request","error_description":"Invalid redirect_uri"}`

Any idea why this might be? I don't have much experience with APIs so I don't really know where to start troubleshooting. 

Thanks for any help!

**Comment by lynuhs** [comment]
Hi @mattroumaya,

Have you created an app in order to get client id and secret? https://yourproject.monday.com/apps/manage

**Comment by lynuhs** [comment]
Hi @mattroumaya,

Have you created an app in order to get client id and secret? https://yourproject.monday.com/apps/manage

**Comment by mattroumaya** [comment]
Yep! I did create an app with a client id and secret. I put those values between the quotes for `monday_auth("client_id", "client_seret")`

**Comment by lynuhs** [comment]
Are you on a local environment or are you using R in the cloud? Could you run sessionInfo() and share the results?

**Comment by mattroumaya** [comment]
@lynuhs sorry to keep this hanging out! I no longer use Monday.com so I'll close this out, but think that I probably didn't have the correct permissions to run `monday_auth()`.
